=== apache/causeway/incubator/clients/kroviz/src/main/resources/bootstrap3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Licensed to the Apache Software Foundation (ASF) under one or more contributor
	license agreements. See the NOTICE file distributed with this work for additional
	information regarding copyright ownership. The ASF licenses this file to
	you under the Apache License, Version 2.0 (the "License"); you may not use
	this file except in compliance with the License. You may obtain a copy of
	the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required
	by applicable law or agreed to in writing, software distributed under the
	License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
	OF ANY KIND, either express or implied. See the License for the specific
	language governing permissions and limitations under the License. -->
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:cpt="http://causeway.apache.org/applib/layout/component"
        xmlns:tns="http://causeway.apache.org/applib/layout/grid/bootstrap3"
        elementFormDefault="qualified"
        targetNamespace="http://causeway.apache.org/applib/layout/grid/bootstrap3"
        version="1.0">

    <xs:import
            namespace="http://causeway.apache.org/applib/layout/component"
            schemaLocation="../../component/component.xsd"/>

    <xs:import
            namespace="http://causeway.apache.org/applib/layout/links"
            schemaLocation="../../links/links.xsd"/>

    <xs:element name="clearFixHidden" type="tns:clearFixHidden"/>

    <xs:element name="clearFixVisible" type="tns:clearFixVisible"/>

    <xs:element name="col" type="tns:col"/>

    <xs:element name="grid" type="tns:grid"/>

    <xs:complexType name="grid">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="row" type="tns:row"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="metadataError" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="cssClass" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="row">
        <xs:complexContent>
            <xs:extension base="tns:bs3ElementAbstract">
                <xs:sequence>
                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                        <xs:element ref="tns:col"/>
                        <xs:element ref="tns:clearFixVisible"/>
                        <xs:element ref="tns:clearFixHidden"/>
                    </xs:choice>
                    <xs:element minOccurs="0" name="metadataError" type="xs:string"/>
                </xs:sequence>
                <xs:attribute name="id" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType abstract="true" name="bs3ElementAbstract">
        <xs:sequence/>
        <xs:attribute name="cssClass" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="col">
        <xs:complexContent>
            <xs:extension base="tns:bs3RowContent">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="sizeSpan" type="tns:sizeSpan"/>
                    <xs:element minOccurs="0" ref="cpt:domainObject"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" ref="cpt:action"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="row" type="tns:row"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="tabGroup" type="tns:tabGroup"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" ref="cpt:fieldSet"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" ref="cpt:collection"/>
                    <xs:element minOccurs="0" name="metadataError" type="xs:string"/>
                </xs:sequence>
                <xs:attribute name="id" type="xs:string"/>
                <xs:attribute name="span" type="xs:int" use="required"/>
                <xs:attribute name="unreferencedActions" type="xs:boolean"/>
                <xs:attribute name="unreferencedCollections" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType abstract="true" name="bs3RowContent">
        <xs:complexContent>
            <xs:extension base="tns:bs3ElementAbstract">
                <xs:sequence/>
                <xs:attribute name="size" type="tns:size"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="sizeSpan">
        <xs:all/>
        <xs:attribute name="offset" type="xs:boolean"/>
        <xs:attribute name="size" type="tns:size" use="required"/>
        <xs:attribute name="span" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:complexType name="tabGroup">
        <xs:complexContent>
            <xs:extension base="tns:bs3ElementAbstract">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="tab" type="tns:tab"/>
                    <xs:element minOccurs="0" name="metadataError" type="xs:string"/>
                </xs:sequence>
                <xs:attribute name="collapseIfOne" type="xs:boolean"/>
                <xs:attribute name="unreferencedCollections" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="tab">
        <xs:complexContent>
            <xs:extension base="tns:bs3ElementAbstract">
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="row" type="tns:row"/>
                </xs:sequence>
                <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="clearFixVisible">
        <xs:complexContent>
            <xs:extension base="tns:bs3ClearFix">
                <xs:sequence/>
                <xs:attribute name="cssDisplay" type="tns:cssDisplay" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType abstract="true" name="bs3ClearFix">
        <xs:complexContent>
            <xs:extension base="tns:bs3RowContent">
                <xs:sequence/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="clearFixHidden">
        <xs:complexContent>
            <xs:extension base="tns:bs3ClearFix">
                <xs:sequence/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="size">
        <xs:restriction base="xs:string">
            <xs:enumeration value="XS"/>
            <xs:enumeration value="SM"/>
            <xs:enumeration value="MD"/>
            <xs:enumeration value="LG"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cssDisplay">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BLOCK"/>
            <xs:enumeration value="INLINE"/>
            <xs:enumeration value="INLINE_BLOCK"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== apache/causeway/extensions/security/secman/applib/src/main/java/org/apache/isis/extensions/secman/applib/tenancy/man/ApplicationTenancyManager.layout.fallback.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- Licensed to the Apache Software Foundation (ASF) under one or more contributor
	license agreements. See the NOTICE file distributed with this work for additional
	information regarding copyright ownership. The ASF licenses this file to
	you under the Apache License, Version 2.0 (the "License"); you may not use
	this file except in compliance with the License. You may obtain a copy of
	the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required
	by applicable law or agreed to in writing, software distributed under the
	License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
	OF ANY KIND, either express or implied. See the License for the specific
	language governing permissions and limitations under the License. -->
<bs:grid
	xsi:schemaLocation="http://isis.apache.org/applib/layout/component https://causeway.apache.org/applib/layout-v1/component/component.xsd   http://isis.apache.org/applib/layout/grid/bootstrap3 https://causeway.apache.org/applib/layout-v1/grid/bootstrap3/bootstrap3.xsd"
	xmlns:bs="http://isis.apache.org/applib/layout/grid/bootstrap3"
	xmlns:cpt="http://isis.apache.org/applib/layout/component"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<bs:row>
		<bs:col span="6">
			<cpt:domainObject />
		</bs:col>
		<bs:col span="6" unreferencedActions="true">
			<bs:tabGroup>
				<bs:tab name="Identity">
					<bs:row>
						<bs:col span="12">
							<cpt:fieldSet name="Identity" id="identity" />
						</bs:col>
					</bs:row>
				</bs:tab>
				<bs:tab name="Other">
					<bs:row>
						<bs:col span="12">
							<cpt:fieldSet name="Other" id="other"
								unreferencedProperties="true" />
						</bs:col>
					</bs:row>
				</bs:tab>
				<bs:tab name="Metadata">
					<bs:row>
						<bs:col span="12">
							<cpt:fieldSet name="Metadata" id="metadata" />
						</bs:col>
					</bs:row>
				</bs:tab>
			</bs:tabGroup>
		</bs:col>
	</bs:row>
	<bs:row>
		<bs:col span="12">
			<bs:tabGroup unreferencedCollections="true">
				<bs:tab name="All Tenancies">
					<bs:row>
						<bs:col span="12" size="MD" />
					</bs:row>
				</bs:tab>
			</bs:tabGroup>
		</bs:col>
	</bs:row>
</bs:grid>

=== apache/causeway/regressiontests/stable-layouts/src/test/java/org/apache/isis/regressiontests/layouts/integtest/model/SimpleObject.layout.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  ~  Licensed to the Apache Software Foundation (ASF) under one
  ~  or more contributor license agreements.  See the NOTICE file
  ~  distributed with this work for additional information
  ~  regarding copyright ownership.  The ASF licenses this file
  ~  to you under the Apache License, Version 2.0 (the
  ~  "License"); you may not use this file except in compliance
  ~  with the License.  You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~  Unless required by applicable law or agreed to in writing,
  ~  software distributed under the License is distributed on an
  ~  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~  KIND, either express or implied.  See the License for the
  ~  specific language governing permissions and limitations
  ~  under the License.
  ~
  -->

<bs:grid xsi:schemaLocation="http://isis.apache.org/applib/layout/component https://causeway.apache.org/applib/layout-v1/component/component.xsd http://isis.apache.org/applib/layout/grid/bootstrap3 https://causeway.apache.org/applib/layout-v1/grid/bootstrap3/bootstrap3.xsd" xmlns:c="http://isis.apache.org/applib/layout/component" xmlns:bs="http://isis.apache.org/applib/layout/grid/bootstrap3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <bs:row>
        <bs:col span="12" unreferencedActions="true">
            <c:domainObject bookmarking="AS_ROOT"/>
        </bs:col>
    </bs:row>
    <bs:row>
        <bs:col span="6">
            <bs:row>
                <bs:col span="12">
                    <bs:tabGroup>
                        <bs:tab name="Identity">
                            <bs:row>
                                <bs:col span="12">
                                    <c:fieldSet name="Identity" id="identity"/>
                                </bs:col>
                            </bs:row>
                        </bs:tab>
                        <bs:tab name="Other">
                            <bs:row>
                                <bs:col span="12">
                                    <c:fieldSet name="Other" id="other" unreferencedProperties="true"/>
                                </bs:col>
                            </bs:row>
                        </bs:tab>
                        <bs:tab name="Metadata">
                            <bs:row>
                                <bs:col span="12">
                                    <c:fieldSet name="Metadata" id="metadata"/>
                                </bs:col>
                            </bs:row>
                        </bs:tab>
                    </bs:tabGroup>
                </bs:col>
                <bs:col span="12">
                    <c:fieldSet name="Details" id="details"/>
                </bs:col>
            </bs:row>
        </bs:col>
        <bs:col span="6">
            <bs:tabGroup  unreferencedCollections="true">
            </bs:tabGroup>
        </bs:col>
    </bs:row>
</bs:grid>

=== apache/causeway/extensions/core/commandlog/applib/src/main/java/org/apache/causeway/extensions/commandlog/applib/dom/replay/CommandReplayManager.layout.xml
<?xml version="1.0" encoding="UTF-8"?><bs:grid xmlns:bs="https://causeway.apache.org/applib/layout/grid/bootstrap3" xmlns:lnk="https://causeway.apache.org/applib/layout/links" xmlns:cpt="https://causeway.apache.org/applib/layout/component" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://causeway.apache.org/applib/layout/component https://causeway.apache.org/applib/layout/component/component.xsd https://causeway.apache.org/applib/layout/links https://causeway.apache.org/applib/layout/links/links.xsd https://causeway.apache.org/applib/layout/grid/bootstrap3 https://causeway.apache.org/applib/layout/grid/bootstrap3/bootstrap3.xsd">
    <bs:row>
        <bs:col span="8" unreferencedActions="true">
            <cpt:domainObject/>
        </bs:col>
        <bs:col span="4">
            <bs:tabGroup>
                <bs:tab name="Identity">
                    <bs:row>
                        <bs:col span="12">
                            <cpt:fieldSet name="Identity" id="identity"/>
                        </bs:col>
                    </bs:row>
                </bs:tab>
                <bs:tab name="Other">
                    <bs:row>
                        <bs:col span="12">
                            <cpt:fieldSet name="Other" id="other" unreferencedProperties="true"/>
                        </bs:col>
                    </bs:row>
                </bs:tab>
                <bs:tab name="Metadata">
                    <bs:row>
                        <bs:col span="12">
                            <cpt:fieldSet name="Metadata" id="metadata"/>
                        </bs:col>
                    </bs:row>
                </bs:tab>
            </bs:tabGroup>
        </bs:col>
    </bs:row>
    <bs:row>
        <bs:col span="12">
            <bs:row>
                <bs:col span="12" size="MD">
                    <cpt:collection defaultView="table" paged="15" id="notYetReplayed"/>
                </bs:col>
            </bs:row>
        </bs:col>
    </bs:row>
    <bs:row>
        <bs:col span="12">
            <bs:tabGroup unreferencedCollections="true">
            </bs:tabGroup>
        </bs:col>
    </bs:row>
</bs:grid>
